#!/bin/bash

### Color
alias lsa='ls -a'
alias ll='ls -l -a'
alias ls='ls --color=auto'
alias grep='grep --color=auto'

### Shorthands
alias c='clear'
alias e='exit'
alias q='exit'

### Git
alias g-conflicts='git diff --name-only --diff-filter=U --relative'
alias g-count='git rev-list --left-right --count master...'
alias g-show-commits='git rev-list --left-right --pretty=oneline master...'
alias g-tree='git ls-tree --name-only -r HEAD'

### Program shortcuts
if [[ -x $(which lazygit) ]]; then
  alias lg='lazygit'
fi 
if [[ -x $(which zoxide) ]]; then
  alias z='zoxide'
fi 
if [[ -x $(which openconnect) ]]; then
  alias vpn='sudo openconnect vpn.ntnu.no'
fi 
if [[ -x $(which nvim) ]]; then
  alias vi='nvim'
fi 
if [[ -x $(which nnn) ]]; then
  alias n='nnn -de'
fi 

### Better ls
if [[ -x $(which exa) ]]; then
  alias ls='exa -l --color=always --group-directories-first'  # list non dotfiles
  alias ll='exa -al --color=always --group-directories-first' # list all
  alias lc='exa -a --color=always --group-directories-first'  # list compact
  alias lt='exa -aT --color=always --group-directories-first' # tree listing
  function getdotfiles() { exa -al --color=always --group-directories-first | awk '$NF ~ /^\./';}
fi

### Platform specific
if [ "$(uname -s)" == "Linux" ]; then
  alias code='code -enable-features=UseOzonePlatform -ozone-platform=wayland'
fi

if [ "$(uname -s)" == "Darwin" ]; then
  alias bs='brew services'
fi

