#!/bin/bash

alias ls='ls --color=auto'
alias lsa='ls -a'
alias ll='ls -l -a'

alias c='clear'
alias e='exit'

alias z='zoxide'
alias lg='lazygit'
alias vi='nvim'
alias t='tmux'

alias gs='git status'
alias ga='git add'
alias gr='git rm' 
alias gc='git commit'
alias gb='git branch -vv'
alias gr='git remote -vv'
alias gl='git log --graph --all'
alias gd='git diff'
alias gr='git restore'

alias bs='brew services'
