#!/bin/bash


git_prompt() {
    local branch="$(git symbolic-ref HEAD 2> /dev/null | cut -d'/' -f3)"
    local master_or_main="$(git branch 2> /dev/null | awk -F ' +' '! /\(no branch\)/ {print $2}' | grep -E "(master|main)")"
    stats="$(git rev-list --count --left-right origin/${master_or_main}... 2> /dev/null)"
    local down="$( echo ${stats} | awk '{ print $1}')"
    local up="$( echo ${stats} | awk '{ print $2}')"
    [ -n "${branch}" ] && echo "(${branch} ${down}↓ ${up}↑)"
}

PS1='\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\w\[\033[00m\] \n $(git_prompt) '

### Alias definitions.
source ~/.config/bash/aliasesrc

### Editor
export VISUAL=nvim
export EDITOR=nvim

### Hisotry
shopt -s histappend # Append to the history file, don't overwrite it
export HISTFILESIZE=
export HISTSIZE=5000

## Other
export BASH_SILENCE_DEPRECATION_WARNING=1
export LC_MESSAGES=en_US.UTF-8
export LANGUAGE=en_US
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8


### Mac specifics
if [ "$(uname -s)" == "Darwin" ]; then
  export PATH=/opt/homebrew/bin/:$PATH
  eval "$(zoxide init bash)"
  ssh-add --apple-load-keychain
fi

### TODO: add check
export PATH=$HOME/.config/tmux/plugins/t-smart-tmux-session-manager/bin:$PATH
### Better cd
if [[ "$(command -v zoxide)" =~ [.*/bin/zoxide$] ]]; then
  eval "$(zoxide init bash)"
fi

### Signing
if [ -x $(which gpg) ]; then
  export GPG_TTY=$(tty)
fi
